// demo/vue-mini/src/pages/cat/cat.vue
<template>
  <view class="cat">
    <text>Cat</text>
  </view>
</template>

<script setup lang="ts">
import * as d3 from 'd3';
import { debounce } from 'lodash';
import { onMounted } from 'vue';
import './index.scss';

onMounted(() => {
  console.log('Page loaded.');
});

console.log(d3);
console.log(debounce);
</script>

<style lang="scss">
@import './index.scss';
</style>

// demo/react-mini/src/pages/cat/cat.tsx
import { View, Text } from '@tarojs/components';
import { useLoad } from '@tarojs/taro';
import * as d3 from 'd3';
import { debounce } from 'lodash';
import './index.scss';

export default function Cat() {
  useLoad(() => {
    console.log('Page loaded.')
  })

  console.log(d3)
  console.log(debounce)

  return (
    <View className='cat'>
      <Text>Cat</Text>
    </View>
  )
}
