// demo/react-mini/src/pages/fish/index.tsx
import { View, Text } from '@tarojs/components';
import { useLoad } from '@tarojs/taro';
import * as echarts from 'echarts';

import './index.scss'

export default function Fish() {
  useLoad(() => {
    console.log('Page loaded.')
  })

  console.log(echarts)

  return (
    <View className='fish'>
      <Text>Fish</Text>
    </View>
  )
}

// demo/vue-mini/src/pages/fish/index.vue
<template>
  <view class="fish">
    <text>Fish</text>
  </view>
</template>

<script setup lang="ts">
import { useLoad } from '@tarojs/taro';
import * as echarts from 'echarts';
import './index.scss';

useLoad(() => {
  console.log('Page loaded.');
});

console.log(echarts);
</script>

<style lang="scss">
@import './index.scss';
</style>
